version: "3"
services:
  nginx-magnautos:
    image: nginx:latest
    container_name: nginx-magnautos
    volumes:
      - ./:/var/www/html:cached
      #- ./magnautos.conf:/etc/nginx/conf.d/default.conf
      - ./magnautos.conf:/etc/nginx/conf.d/magnautos.local.conf
      - ./magnautos-admin.conf:/etc/nginx/conf.d/admin.magnautos.local.conf
    ports:
      - "8800:80"
    networks:
      internal:
        aliases:
          - magnautos.local
  php-magnautos:
    container_name: php-magnautos
    #image: magnauto-php-image:Dockerfile
    build:
      dockerfile: ./php/Dockerfile
      context: .
    volumes:
      - ./:/var/www/html
    networks:
      - internal
  database-magnautos:
    container_name: database-magnautos
    image: mysql:5.7
    restart: always
    platform: linux/amd64
    environment:
      MYSQL_DATABASE: 'magnautos'
      MYSQL_USER: 'magnus'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - 33306:3306
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping" ]
    volumes:
      - ./.data/mysql:/var/lib/mysql
    networks:
      - internal
networks:
  internal:
    driver: bridge
